GET http://localhost:8080/items/
Content-Type: application/json

###

POST http://localhost:8081/signup
Content-Type: application/json

{
  "username": "u10",
  "password": "EasyPassword",
  "email": "auprutyanova@gmail.com"
}

###

POST http://localhost:8080/signup
Content-Type: application/json

{
  "username": "USer_2",
  "password": "EasyPassword",
  "email": "mail"
}

###

POST http://localhost:8081/signin
Content-Type: application/json

{
  "username": "admin",
  "password": "adminPassword"
}

###

POST http://localhost:8081/signin
Content-Type: application/json

{
"username": "user1",
"password": "EasyPassword"
}

###

GET http://localhost:8080/items/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlZTNmNjQ3NzYyNWQ4MDAxMzgyMTE1MyJ9LCJpYXQiOjE1OTIwMDg2OTgsImV4cCI6MTU5MjMwODY5OH0.mVzQkrpnG0EnCF5xGql_Ta_4j9VvgvpfPJDpKuqF0dE"
}


###

GET http://localhost:8080/items/
Content-Type: application/json

{

  "token": "12343"
}

###

POST http://localhost:8081/refresh
Content-Type: application/json

{
  "refresh": "8d22e7bed7e813a9eec6d3b4a257a70f4d1d04963a42e04bb54ae26b3054a578"
}

###