POST http://localhost:8081/signup
Content-Type: application/json

{
  "username": "newUser32",
  "password": "EasyPassword",
  "email": "auprutyanova@gmail.com"
}

###

POST http://localhost:8081/signin
Content-Type: application/json

{
  "username": "newUser32",
  "password": "EasyPassword"
}

###

