GET http://localhost:8080/items/

###

POST http://localhost:8080/items
Content-Type: application/json

{
    "name" : "computer",
    "category" : "smth"
}

###

GET http://localhost:8080/items

###

POST http://localhost:8080/items?name=TV_1

###

GET http://localhost:8080/items/2

###

PUT http://localhost:8080/items/2?category=cat

###

GET http://localhost:8080/items

###

DELETE http://localhost:8080/items/1/

###

GET http://localhost:8080/items/

###
