GET http://localhost:8080/items/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlZTQ5NmU3NjkzYjJmMDAxM2YzZTJlZiJ9LCJpYXQiOjE1OTIwMzkxNDcsImV4cCI6MTU5MjMzOTE0N30.73AiZuDE4TVnezkPoRVH6JpKvcLGUU1EoWI6J1hS67E"
}

###

POST http://localhost:8080/items/
Content-Type: application/json

{
  "name" : "my_omputer",
  "category" : "smth",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlZTQ5NmU3NjkzYjJmMDAxM2YzZTJlZiJ9LCJpYXQiOjE1OTIwMzkxNDcsImV4cCI6MTU5MjMzOTE0N30.73AiZuDE4TVnezkPoRVH6JpKvcLGUU1EoWI6J1hS67E"
}

###

GET http://localhost:8080/items
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlYWM3ZmM4MmZmN2Y2MDAxOTI1ZTc0YSJ9LCJpYXQiOjE1ODgzNjMyMjgsImV4cCI6MTU4ODY2MzIyOH0.ZxyUdLkI-1suuTE929nmuFW_JodKyulVKaMcfRsTFPk"
}

###

POST http://localhost:8080/items?name=TV_2
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlZTQ3ZWQwYmQ2MDRmMDAxMzdjNjI1OCJ9LCJpYXQiOjE1OTIwMzMwMzEsImV4cCI6MTU5MjMzMzAzMX0.1d2GcPEVF6aqqDcvCu3JlwEMk656HqyW0JLV1exdJPY"
}

###

GET http://localhost:8080/items/5ee47f619cf81e0012abaf28
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlZTQ3ZWQwYmQ2MDRmMDAxMzdjNjI1OCJ9LCJpYXQiOjE1OTIwMzMwMzEsImV4cCI6MTU5MjMzMzAzMX0.1d2GcPEVF6aqqDcvCu3JlwEMk656HqyW0JLV1exdJPY"
}

###

PUT http://localhost:8080/items/5ead37f9301ac3001ae8e35e?category=cat
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlYWM3ZmM4MmZmN2Y2MDAxOTI1ZTc0YSJ9LCJpYXQiOjE1ODgzNjMyMjgsImV4cCI6MTU4ODY2MzIyOH0.ZxyUdLkI-1suuTE929nmuFW_JodKyulVKaMcfRsTFPk"
}

###

GET http://localhost:8080/items/5eac806d2ff7f6001925e74c
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlYWM3ZmM4MmZmN2Y2MDAxOTI1ZTc0YSJ9LCJpYXQiOjE1ODgzNjMyMjgsImV4cCI6MTU4ODY2MzIyOH0.ZxyUdLkI-1suuTE929nmuFW_JodKyulVKaMcfRsTFPk"
}

###

DELETE http://localhost:8080/items/5ead37f9301ac3001ae8e35e/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJJZCI6IjVlYWM3ZmM4MmZmN2Y2MDAxOTI1ZTc0YSJ9LCJpYXQiOjE1ODgzNjMyMjgsImV4cCI6MTU4ODY2MzIyOH0.ZxyUdLkI-1suuTE929nmuFW_JodKyulVKaMcfRsTFPk"
}

###

GET http://localhost:8080/items/

###
